<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

 /**
 * Implements hook_preprocess_html().
 */
function bootstrap_directory_preprocess_html(&$variables) {
  $is_frontpage = \Drupal::service('path.matcher')->isFrontPage();;
  if ($is_frontpage) {
  //echo '<pre>' . print_r($variables,1) . '</pre>';
  //die ;
    $variables['attributes']['class'][] = 'frontpage';
  }
}